//•	16. Write a program to walk through a directory tree and display file names using Files.walk().
package day_10_FileHandling;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class WalkDirectory {

	public static void main(String[] args) throws IOException {
		// TODO Auto-generated method stub
		Files.walk(Paths.get(".")).forEach(System.out::println);
	}

}


//.
//.\.classpath
//.\.project
//.\.settings
//.\.settings\org.eclipse.core.resources.prefs
//.\.settings\org.eclipse.jdt.core.prefs
//.\bin
//.\bin\day_10_FileHandling
//.\bin\day_10_FileHandling\AppendToFile.class
//.\bin\day_10_FileHandling\CopyFile.class
//.\bin\day_10_FileHandling\CopyFiles.class
//.\bin\day_10_FileHandling\Counts.class
//.\bin\day_10_FileHandling\CreateFile.class
//.\bin\day_10_FileHandling\DeserializeEmployee.class
//.\bin\day_10_FileHandling\Employee.class
//.\bin\day_10_FileHandling\FileExistCheck.class
//.\bin\day_10_FileHandling\FileOps.class
//.\bin\day_10_FileHandling\FileSizeCheck.class
//.\bin\day_10_FileHandling\FilesWriteAppend.class
//.\bin\day_10_FileHandling\FilterTextFiles.class
//.\bin\day_10_FileHandling\ListFiles.class
//.\bin\day_10_FileHandling\ReadAllLines.class
//.\bin\day_10_FileHandling\ReadFile.class
//.\bin\day_10_FileHandling\ReadWithScanner.class
//.\bin\day_10_FileHandling\SerializeEmployee.class
//.\bin\day_10_FileHandling\SerializeStudent.class
//.\bin\day_10_FileHandling\Student.class
//.\bin\day_10_FileHandling\WalkDirectory.class
//.\bin\day_10_FileHandling\WordCount.class
//.\bin\day_10_FileHandling\WriteToFile.class
//.\bin\day_11_JDBC
//.\bin\day_11_JDBC\CountRows.class
//.\bin\day_11_JDBC\DBConnect.class
//.\bin\day_11_JDBC\DeleteStudent.class
//.\bin\day_11_JDBC\DisplayStudents.class
//.\bin\day_11_JDBC\EmployeeCRUD.class
//.\bin\day_11_JDBC\InsertMultiStudents.class
//.\bin\day_11_JDBC\InsertStudent.class
//.\bin\day_11_JDBC\LoginSystem.class
//.\bin\day_11_JDBC\PerGrtr75.class
//.\bin\day_11_JDBC\ReportGenerator.class
//.\bin\day_11_JDBC\SearchStudent.class
//.\bin\day_11_JDBC\SortStudents.class
//.\bin\day_11_JDBC\UpdateStudent.class
//.\bin\day_2
//.\bin\day_2\Count_digits.class
//.\bin\day_2\Diamond.class
//.\bin\day_2\DoubleToInt.class
//.\bin\day_2\Even_2_50.class
//.\bin\day_2\Factorial.class
//.\bin\day_2\Fibinocci.class
//.\bin\day_2\if_else_switch_demo.class
//.\bin\day_2\Multiplication_of_17.class
//.\bin\day_2\OperatorDemo.class
//.\bin\day_2\Palindrome.class
//.\bin\day_2\Prime_or_not.class
//.\bin\day_2\PrimitiveTypes.class
//.\bin\day_2\Pyramid.class
//.\bin\day_2\Reverse_numbers.class
//.\bin\day_2\Square_1_10.class
//.\bin\day_2\Sum_of_digits.class
//.\bin\day_2\Sum_of_numbers.class
//.\bin\day_3_array
//.\bin\day_3_array\copyArray.class
//.\bin\day_3_array\count_even_odd.class
//.\bin\day_3_array\Frequency.class
//.\bin\day_3_array\Max_min.class
//.\bin\day_3_array\merge_sort.class
//.\bin\day_3_array\Palindrome.class
//.\bin\day_3_array\PrintPrime.class
//.\bin\day_3_array\printReverse.class
//.\bin\day_3_array\Remove_duplicate.class
//.\bin\day_3_array\Rotate.class
//.\bin\day_3_array\Search_num.class
//.\bin\day_3_array\Second_highest.class
//.\bin\day_3_array\segregate_even_odd.class
//.\bin\day_3_array\SortArray.class
//.\bin\day_3_array\Sum_of_Elements.class
//.\bin\day_3_string
//.\bin\day_3_string\Count_digit_letter_space_specialchar.class
//.\bin\day_3_string\Count_vowels.class
//.\bin\day_3_string\Count_words.class
//.\bin\day_3_string\Frequency_of_character.class
//.\bin\day_3_string\Palindrome.class
//.\bin\day_3_string\Remove_whitespace.class
//.\bin\day_3_string\Replace_space_with_hyphen.class
//.\bin\day_3_string\Sentence_to_words.class
//.\bin\day_3_string\sort_alphabetically.class
//.\bin\day_3_string\Start_j_end_a.class
//.\bin\day_3_variables
//.\bin\day_3_variables\Addition.class
//.\bin\day_3_variables\Employee.class
//.\bin\day_3_variables\RectangleArea.class
//.\bin\day_3_variables\SimpleInterest.class
//.\bin\day_3_variables\Swap.class
//.\bin\day_4
//.\bin\day_4\Accountant.class
//.\bin\day_4\After_12th.class
//.\bin\day_4\Baleno_FiveSeater_Petrol_Four_wheeler.class
//.\bin\day_4\BBA.class
//.\bin\day_4\BCA.class
//.\bin\day_4\BDS.class
//.\bin\day_4\Cardiac.class
//.\bin\day_4\Child.class
//.\bin\day_4\course.class
//.\bin\day_4\CS.class
//.\bin\day_4\Doctor.class
//.\bin\day_4\Documentation.class
//.\bin\day_4\Endo.class
//.\bin\day_4\Engineering.class
//.\bin\day_4\FiveSeater_Petrol_Four_wheeler.class
//.\bin\day_4\Four_wheeler.class
//.\bin\day_4\Gynac.class
//.\bin\day_4\Hospital.class
//.\bin\day_4\Hospitals.class
//.\bin\day_4\Hospital_hierar.class
//.\bin\day_4\IT.class
//.\bin\day_4\MBBS.class
//.\bin\day_4\Mechanical.class
//.\bin\day_4\Medical.class
//.\bin\day_4\multilevel_vehicle.class
//.\bin\day_4\Nurse.class
//.\bin\day_4\OPD.class
//.\bin\day_4\Operation.class
//.\bin\day_4\Other_Courses.class
//.\bin\day_4\Parent.class
//.\bin\day_4\Patient.class
//.\bin\day_4\Payments.class
//.\bin\day_4\Petrol_Four_wheeler.class
//.\bin\day_4\Super.class
//.\bin\day_4\TestHospital.class
//.\bin\day_4\Vehicle.class
//.\bin\day_4_other
//.\bin\day_4_other\Bike.class
//.\bin\day_4_other\Car.class
//.\bin\day_4_other\Person.class
//.\bin\day_4_other\Person_info.class
//.\bin\day_4_other\Professor.class
//.\bin\day_4_other\SmartDevice.class
//.\bin\day_4_other\SmartPhone.class
//.\bin\day_4_other\SmartSpeaker.class
//.\bin\day_4_other\SmartWatch.class
//.\bin\day_4_other\Smart_Device_demo.class
//.\bin\day_4_other\Student.class
//.\bin\day_4_other\TeachingAssistant.class
//.\bin\day_4_other\Truck.class
//.\bin\day_4_other\Vehicle.class
//.\bin\day_4_other\Vehicle_demo.class
//.\bin\day_4_polymorphism
//.\bin\day_4_polymorphism\Bank.class
//.\bin\day_4_polymorphism\Bank_interest.class
//.\bin\day_4_polymorphism\Bike.class
//.\bin\day_4_polymorphism\Calculator.class
//.\bin\day_4_polymorphism\Circle.class
//.\bin\day_4_polymorphism\HDFC.class
//.\bin\day_4_polymorphism\ICICI.class
//.\bin\day_4_polymorphism\Rectangle.class
//.\bin\day_4_polymorphism\SBI.class
//.\bin\day_4_polymorphism\Shape.class
//.\bin\day_4_polymorphism\Shapes.class
//.\bin\day_4_polymorphism\Vehicle.class
//.\bin\day_4_polymorphism\Vehicle_demo.class
//.\bin\day_5_encapsulation
//.\bin\day_5_encapsulation\BankAccount.class
//.\bin\day_5_encapsulation\Locker$SecurityManager.class
//.\bin\day_5_encapsulation\Locker.class
//.\bin\day_5_encapsulation\ProductDemo$Product$Builder.class
//.\bin\day_5_encapsulation\ProductDemo$Product.class
//.\bin\day_5_encapsulation\ProductDemo.class
//.\bin\day_5_encapsulation\Rectangle.class
//.\bin\day_5_encapsulation\Student.class
//.\bin\day_5_interface
//.\bin\day_5_interface\AGGREGATE.class
//.\bin\day_5_interface\BackwardSequence.class
//.\bin\day_5_interface\FACTORIAL$Factorial.class
//.\bin\day_5_interface\FACTORIAL.class
//.\bin\day_5_interface\LambdaSumExample.class
//.\bin\day_5_interface\Main.class
//.\bin\day_5_interface\MAXMIN.class
//.\bin\day_5_interface\MovableShapeSimulation$Movable.class
//.\bin\day_5_interface\MovableShapeSimulation$MovableCircle.class
//.\bin\day_5_interface\MovableShapeSimulation$MovablePoint.class
//.\bin\day_5_interface\MovableShapeSimulation$MovableRectangle.class
//.\bin\day_5_interface\MovableShapeSimulation.class
//.\bin\day_5_interface\OddEven.class
//.\bin\day_5_interface\SORTSTRINGS.class
//.\bin\day_5_interface\StringIsEmplty.class
//.\bin\day_5_interface\SumCalculator.class
//.\bin\day_5_interface\SumOperation.class
//.\bin\day_5_interface\UPPERCASE.class
//.\bin\Day_6_typeConversion
//.\bin\Day_6_typeConversion\Animal.class
//.\bin\Day_6_typeConversion\CalculatorOverrideTest.class
//.\bin\Day_6_typeConversion\CalculatorSwitchTest.class
//.\bin\Day_6_typeConversion\compass.class
//.\bin\Day_6_typeConversion\CompoundAssignment.class
//.\bin\Day_6_typeConversion\DaysOfWeek.class
//.\bin\Day_6_typeConversion\Difficulty.class
//.\bin\Day_6_typeConversion\Direction.class
//.\bin\Day_6_typeConversion\Dog.class
//.\bin\Day_6_typeConversion\ExceptionDemo.class
//.\bin\Day_6_typeConversion\FileReadDemo.class
//.\bin\Day_6_typeConversion\Game.class
//.\bin\Day_6_typeConversion\GameTest.class
//.\bin\Day_6_typeConversion\InheritanceCasting.class
//.\bin\Day_6_typeConversion\KnowledgeLevel.class
//.\bin\Day_6_typeConversion\KnowledgeTest.class
//.\bin\Day_6_typeConversion\MultiExceptionDemo.class
//.\bin\Day_6_typeConversion\OddChecker.class
//.\bin\Day_6_typeConversion\OddNumberException.class
//.\bin\Day_6_typeConversion\OperationOverride$1.class
//.\bin\Day_6_typeConversion\OperationOverride$2.class
//.\bin\Day_6_typeConversion\OperationOverride$3.class
//.\bin\Day_6_typeConversion\OperationOverride$4.class
//.\bin\Day_6_typeConversion\OperationOverride.class
//.\bin\Day_6_typeConversion\OperationSwitch.class
//.\bin\Day_6_typeConversion\PriorityLevel.class
//.\bin\Day_6_typeConversion\PriorityTest.class
//.\bin\Day_6_typeConversion\Shape$1.class
//.\bin\Day_6_typeConversion\Shape$2.class
//.\bin\Day_6_typeConversion\Shape$3.class
//.\bin\Day_6_typeConversion\Shape$4.class
//.\bin\Day_6_typeConversion\Shape.class
//.\bin\Day_6_typeConversion\ShapeTest.class
//.\bin\Day_6_typeConversion\State.class
//.\bin\Day_6_typeConversion\StringConversion.class
//.\bin\Day_6_typeConversion\TemperatureConverter.class
//.\bin\Day_6_typeConversion\TrafficLight$1.class
//.\bin\Day_6_typeConversion\TrafficLight$2.class
//.\bin\Day_6_typeConversion\TrafficLight$3.class
//.\bin\Day_6_typeConversion\TrafficLight.class
//.\bin\Day_6_typeConversion\TrafficSimulation.class
//.\bin\Day_6_typeConversion\TypeConversion.class
//.\bin\Day_6_typeConversion\weekday.class
//.\bin\day_7
//.\bin\day_7\AlternatePrint.class
//.\bin\day_7\AssignNewObject.class
//.\bin\day_7\BankAccount.class
//.\bin\day_7\BankExample.class
//.\bin\day_7\Box.class
//.\bin\day_7\Boxs.class
//.\bin\day_7\BoxTest.class
//.\bin\day_7\CallableExample.class
//.\bin\day_7\CallByValueDemo.class
//.\bin\day_7\DaemonThreadExample.class
//.\bin\day_7\EvenOddThreads.class
//.\bin\day_7\IsAliveExample.class
//.\bin\day_7\Item.class
//.\bin\day_7\JoinExample.class
//.\bin\day_7\ModifyObject.class
//.\bin\day_7\MyRunnable.class
//.\bin\day_7\MyThread.class
//.\bin\day_7\PassByValueDemo1.class
//.\bin\day_7\PassByValueDemo2.class
//.\bin\day_7\PassByValueDemo3.class
//.\bin\day_7\Person.class
//.\bin\day_7\ProducerConsumer.class
//.\bin\day_7\ProducerConsumerTest.class
//.\bin\day_7\RaceCondition.class
//.\bin\day_7\RunnableExample.class
//.\bin\day_7\SimulateCallByReference.class
//.\bin\day_7\SleepExample.class
//.\bin\day_7\StopThreadExample$MyTask.class
//.\bin\day_7\StopThreadExample.class
//.\bin\day_7\Student.class
//.\bin\day_7\SyncBlockExample.class
//.\bin\day_7\SyncExample.class
//.\bin\day_7\ThreadExample1.class
//.\bin\day_7\ThreadGroupExample.class
//.\bin\day_7\ThreadPriority.class
//.\bin\day_7\TwoThreads.class
//.\bin\day_7\UpdateMarks.class
//.\bin\day_7\WaitNotifyAllExample$Shared.class
//.\bin\day_7\WaitNotifyAllExample.class
//.\bin\day_7\WrapperExamples.class
//.\bin\day_7\YieldExample.class
//.\bin\day_8_Collections
//.\bin\day_8_Collections\Copy_ArrayList_toAnother.class
//.\bin\day_8_Collections\Iterate.class
//.\bin\day_8_Collections\Remove_all.class
//.\bin\day_8_Collections\Remove_Element.class
//.\bin\day_8_Collections\Reverse.class
//.\bin\day_8_Collections\Search_Element.class
//.\bin\day_8_Collections\Sort_element.class
//.\bin\day_8_Collections\Student.class
//.\bin\day_8_Collections\Update_element.class
//.\bin\day_8_LinkedList
//.\bin\day_8_LinkedList\Add_First_last.class
//.\bin\day_8_LinkedList\Book.class
//.\bin\day_8_LinkedList\Clone.class
//.\bin\day_8_LinkedList\Display.class
//.\bin\day_8_LinkedList\Insert_at_index.class
//.\bin\day_8_LinkedList\Iterate.class
//.\bin\day_8_LinkedList\LinkedList_ArrayList.class
//.\bin\day_8_LinkedList\Remove_Element.class
//.\bin\day_8_LinkedList\Search.class
//.\bin\day_8_LinkedList\Sort.class
//.\bin\day_8_queue
//.\bin\day_8_queue\BankQueue.class
//.\bin\day_8_queue\BrowserHistory.class
//.\bin\day_8_queue\DequeOperations.class
//.\bin\day_8_queue\EvenNumberFilter.class
//.\bin\day_8_queue\HospitalQueue_prio.class
//.\bin\day_8_queue\Merge_prio.class
//.\bin\day_8_queue\Palindrome_deque.class
//.\bin\day_8_queue\Patient.class
//.\bin\day_8_queue\PrintJob.class
//.\bin\day_8_queue\PrintQueue_prio.class
//.\bin\day_8_queue\TaskManager.class
//.\bin\day_8_Sets
//.\bin\day_8_Sets\LinkedHashSet_Int.class
//.\bin\day_8_Sets\Max_HashSet.class
//.\bin\day_8_Sets\Merge_LinkedHashSet.class
//.\bin\day_8_Sets\String_HashSet.class
//.\bin\day_8_Sets\TreeSetCountries.class
//.\bin\day_8_Sets\TreeSetCustomComparator.class
//.\bin\day_8_Sets\TreeSetNumbers.class
//.\bin\day_8_stack
//.\bin\day_8_stack\BalancedParanthesis.class
//.\bin\day_8_stack\Decimal_binary.class
//.\bin\day_8_stack\Reverse_String.class
//.\bin\day_8_stack\StackDemo.class
//.\bin\day_8_Vector
//.\bin\day_8_Vector\Copy.class
//.\bin\day_8_Vector\Sum.class
//.\bin\day_8_Vector\Vector_Demo.class
//.\bin\day_8_Vector\Vector_strings.class
//.\bin\day_9_Comparable_Comparator
//.\bin\day_9_Comparable_Comparator\Book.class
//.\bin\day_9_Comparable_Comparator\Book2.class
//.\bin\day_9_Comparable_Comparator\City.class
//.\bin\day_9_Comparable_Comparator\Emp.class
//.\bin\day_9_Comparable_Comparator\Employee.class
//.\bin\day_9_Comparable_Comparator\EmployeeDate.class
//.\bin\day_9_Comparable_Comparator\EmpMenu.class
//.\bin\day_9_Comparable_Comparator\Person.class
//.\bin\day_9_Comparable_Comparator\PersonTree.class
//.\bin\day_9_Comparable_Comparator\Product.class
//.\bin\day_9_Comparable_Comparator\Product2.class
//.\bin\day_9_Comparable_Comparator\Products_Sort.class
//.\bin\day_9_Comparable_Comparator\StringSort$1.class
//.\bin\day_9_Comparable_Comparator\StringSort.class
//.\bin\day_9_Comparable_Comparator\Student.class
//.\bin\day_9_Comparable_Comparator\Student2.class
//.\bin\day_9_Comparable_Comparator\Students.class
//.\bin\day_9_Comparable_Comparator\Student_Sort.class
//.\bin\day_9_FileHandling
//.\bin\day_9_FileHandling\AppendToFile.class
//.\bin\day_9_FileHandling\CopyFile.class
//.\bin\day_9_FileHandling\CountWordsLines.class
//.\bin\day_9_FileHandling\DeleteFile.class
//.\bin\day_9_FileHandling\DeserializeStudent.class
//.\bin\day_9_FileHandling\FileProperties.class
//.\bin\day_9_FileHandling\ReadFromFile.class
//.\bin\day_9_FileHandling\ReplaceWord.class
//.\bin\day_9_FileHandling\ReverseFileContent.class
//.\bin\day_9_FileHandling\SearchWord.class
//.\bin\day_9_FileHandling\SerializeStudent.class
//.\bin\day_9_FileHandling\Student.class
//.\bin\day_9_FileHandling\UserInputToFile.class
//.\bin\day_9_FileHandling\WriteToFile.class
//.\copied.txt
//.\copy.txt
//.\data.txt
//.\destination.txt
//.\employee.ser
//.\hello.txt
//.\notes.txt
//.\report.txt
//.\reversed.txt
//.\source.txt
//.\src
//.\src\day_10_FileHandling
//.\src\day_10_FileHandling\AppendToFile.java
//.\src\day_10_FileHandling\CopyFile.java
//.\src\day_10_FileHandling\CopyFiles.java
//.\src\day_10_FileHandling\Counts.java
//.\src\day_10_FileHandling\CreateFile.java
//.\src\day_10_FileHandling\DeserializeEmployee.java
//.\src\day_10_FileHandling\FileExistCheck.java
//.\src\day_10_FileHandling\FileOps.java
//.\src\day_10_FileHandling\FileSizeCheck.java
//.\src\day_10_FileHandling\FilesWriteAppend.java
//.\src\day_10_FileHandling\FilterTextFiles.java
//.\src\day_10_FileHandling\ListFiles.java
//.\src\day_10_FileHandling\ReadAllLines.java
//.\src\day_10_FileHandling\ReadFile.java
//.\src\day_10_FileHandling\ReadWithScanner.java
//.\src\day_10_FileHandling\SerializeEmployee.java
//.\src\day_10_FileHandling\SerializeStudent.java
//.\src\day_10_FileHandling\WalkDirectory.java
//.\src\day_10_FileHandling\WordCount.java
//.\src\day_10_FileHandling\WriteToFile.java
//.\src\day_11_JDBC
//.\src\day_11_JDBC\CountRows.java
//.\src\day_11_JDBC\DBConnect.java
//.\src\day_11_JDBC\DeleteStudent.java
//.\src\day_11_JDBC\DisplayStudents.java
//.\src\day_11_JDBC\EmployeeCRUD.java
//.\src\day_11_JDBC\InsertMultiStudents.java
//.\src\day_11_JDBC\InsertStudent.java
//.\src\day_11_JDBC\LoginSystem.java
//.\src\day_11_JDBC\PerGrtr75.java
//.\src\day_11_JDBC\ReportGenerator.java
//.\src\day_11_JDBC\SearchStudent.java
//.\src\day_11_JDBC\SortStudents.java
//.\src\day_11_JDBC\UpdateStudent.java
//.\src\day_2
//.\src\day_2\Count_digits.java
//.\src\day_2\Diamond.java
//.\src\day_2\DoubleToInt.java
//.\src\day_2\Even_2_50.java
//.\src\day_2\Factorial.java
//.\src\day_2\Fibinocci.java
//.\src\day_2\if_else_switch_demo.java
//.\src\day_2\Multiplication_of_17.java
//.\src\day_2\OperatorDemo.java
//.\src\day_2\Palindrome.java
//.\src\day_2\Prime_or_not.java
//.\src\day_2\PrimitiveTypes.java
//.\src\day_2\Pyramid.java
//.\src\day_2\Reverse_numbers.java
//.\src\day_2\Square_1_10.java
//.\src\day_2\Sum_of_digits.java
//.\src\day_2\Sum_of_numbers.java
//.\src\day_3_array
//.\src\day_3_array\copyArray.java
//.\src\day_3_array\count_even_odd.java
//.\src\day_3_array\Frequency.java
//.\src\day_3_array\Max_min.java
//.\src\day_3_array\merge_sort.java
//.\src\day_3_array\Palindrome.java
//.\src\day_3_array\PrintPrime.java
//.\src\day_3_array\printReverse.java
//.\src\day_3_array\Remove_duplicate.java
//.\src\day_3_array\Rotate.java
//.\src\day_3_array\Search_num.java
//.\src\day_3_array\Second_highest.java
//.\src\day_3_array\segregate_even_odd.java
//.\src\day_3_array\SortArray.java
//.\src\day_3_array\Sum_of_Elements.java
//.\src\day_3_string
//.\src\day_3_string\Count_digit_letter_space_specialchar.java
//.\src\day_3_string\Count_vowels.java
//.\src\day_3_string\Count_words.java
//.\src\day_3_string\Frequency_of_character.java
//.\src\day_3_string\Palindrome.java
//.\src\day_3_string\Remove_whitespace.java
//.\src\day_3_string\Replace_space_with_hyphen.java
//.\src\day_3_string\Sentence_to_words.java
//.\src\day_3_string\sort_alphabetically.java
//.\src\day_3_string\Start_j_end_a.java
//.\src\day_3_variables
//.\src\day_3_variables\Addition.java
//.\src\day_3_variables\Employee.java
//.\src\day_3_variables\RectangleArea.java
//.\src\day_3_variables\SimpleInterest.java
//.\src\day_3_variables\Swap.java
//.\src\day_4
//.\src\day_4\course.java
//.\src\day_4\Hospital_hierar.java
//.\src\day_4\multilevel_vehicle.java
//.\src\day_4\Super.java
//.\src\day_4\TestHospital.java
//.\src\day_4_other
//.\src\day_4_other\Person_info.java
//.\src\day_4_other\Smart_Device_demo.java
//.\src\day_4_other\Vehicle_demo.java
//.\src\day_4_polymorphism
//.\src\day_4_polymorphism\Bank_interest.java
//.\src\day_4_polymorphism\Calculator.java
//.\src\day_4_polymorphism\Shapes.java
//.\src\day_4_polymorphism\Vehicle_demo.java
//.\src\day_5_encapsulation
//.\src\day_5_encapsulation\BankAccount.java
//.\src\day_5_encapsulation\Locker.java
//.\src\day_5_encapsulation\ProductDemo.java
//.\src\day_5_encapsulation\Rectangle.java
//.\src\day_5_encapsulation\Student.java
//.\src\day_5_interface
//.\src\day_5_interface\AGGREGATE.java
//.\src\day_5_interface\BackwardSequence.java
//.\src\day_5_interface\FACTORIAL.java
//.\src\day_5_interface\LambdaSumExample.java
//.\src\day_5_interface\Main.java
//.\src\day_5_interface\MAXMIN.java
//.\src\day_5_interface\MovableShapeSimulation.java
//.\src\day_5_interface\OddEven.java
//.\src\day_5_interface\SORTSTRINGS.java
//.\src\day_5_interface\StringIsEmplty.java
//.\src\day_5_interface\UPPERCASE.java
//.\src\Day_6_typeConversion
//.\src\Day_6_typeConversion\CalculatorOverrideTest.java
//.\src\Day_6_typeConversion\CalculatorSwitchTest.java
//.\src\Day_6_typeConversion\compass.java
//.\src\Day_6_typeConversion\CompoundAssignment.java
//.\src\Day_6_typeConversion\ExceptionDemo.java
//.\src\Day_6_typeConversion\FileReadDemo.java
//.\src\Day_6_typeConversion\GameTest.java
//.\src\Day_6_typeConversion\InheritanceCasting.java
//.\src\Day_6_typeConversion\KnowledgeTest.java
//.\src\Day_6_typeConversion\MultiExceptionDemo.java
//.\src\Day_6_typeConversion\OddChecker.java
//.\src\Day_6_typeConversion\PriorityTest.java
//.\src\Day_6_typeConversion\ShapeTest.java
//.\src\Day_6_typeConversion\StringConversion.java
//.\src\Day_6_typeConversion\TemperatureConverter.java
//.\src\Day_6_typeConversion\TrafficSimulation.java
//.\src\Day_6_typeConversion\TypeConversion.java
//.\src\Day_6_typeConversion\weekday.java
//.\src\day_7
//.\src\day_7\AlternatePrint.java
//.\src\day_7\AssignNewObject.java
//.\src\day_7\BankExample.java
//.\src\day_7\BoxTest.java
//.\src\day_7\CallableExample.java
//.\src\day_7\CallByValueDemo.java
//.\src\day_7\DaemonThreadExample.java
//.\src\day_7\EvenOddThreads.java
//.\src\day_7\IsAliveExample.java
//.\src\day_7\JoinExample.java
//.\src\day_7\ModifyObject.java
//.\src\day_7\PassByValueDemo1.java
//.\src\day_7\PassByValueDemo2.java
//.\src\day_7\PassByValueDemo3.java
//.\src\day_7\ProducerConsumerTest.java
//.\src\day_7\RaceCondition.java
//.\src\day_7\RunnableExample.java
//.\src\day_7\SimulateCallByReference.java
//.\src\day_7\SleepExample.java
//.\src\day_7\StopThreadExample.java
//.\src\day_7\SyncBlockExample.java
//.\src\day_7\SyncExample.java
//.\src\day_7\ThreadExample1.java
//.\src\day_7\ThreadGroupExample.java
//.\src\day_7\ThreadPriority.java
//.\src\day_7\TwoThreads.java
//.\src\day_7\UpdateMarks.java
//.\src\day_7\WaitNotifyAllExample.java
//.\src\day_7\WrapperExamples.java
//.\src\day_7\YieldExample.java
//.\src\day_8_Collections
//.\src\day_8_Collections\Copy_ArrayList_toAnother.java
//.\src\day_8_Collections\Iterate.java
//.\src\day_8_Collections\Remove_all.java
//.\src\day_8_Collections\Remove_Element.java
//.\src\day_8_Collections\Reverse.java
//.\src\day_8_Collections\Search_Element.java
//.\src\day_8_Collections\Sort_element.java
//.\src\day_8_Collections\Student.java
//.\src\day_8_Collections\Update_element.java
//.\src\day_8_LinkedList
//.\src\day_8_LinkedList\Add_First_last.java
//.\src\day_8_LinkedList\Book.java
//.\src\day_8_LinkedList\Clone.java
//.\src\day_8_LinkedList\Display.java
//.\src\day_8_LinkedList\Insert_at_index.java
//.\src\day_8_LinkedList\Iterate.java
//.\src\day_8_LinkedList\LinkedList_ArrayList.java
//.\src\day_8_LinkedList\Remove_Element.java
//.\src\day_8_LinkedList\Search.java
//.\src\day_8_LinkedList\Sort.java
//.\src\day_8_queue
//.\src\day_8_queue\BankQueue.java
//.\src\day_8_queue\BrowserHistory.java
//.\src\day_8_queue\DequeOperations.java
//.\src\day_8_queue\EvenNumberFilter.java
//.\src\day_8_queue\HospitalQueue_prio.java
//.\src\day_8_queue\Merge_prio.java
//.\src\day_8_queue\Palindrome_deque.java
//.\src\day_8_queue\PrintQueue_prio.java
//.\src\day_8_queue\TaskManager.java
//.\src\day_8_Sets
//.\src\day_8_Sets\LinkedHashSet_Int.java
//.\src\day_8_Sets\Max_HashSet.java
//.\src\day_8_Sets\Merge_LinkedHashSet.java
//.\src\day_8_Sets\String_HashSet.java
//.\src\day_8_Sets\TreeSetCountries.java
//.\src\day_8_Sets\TreeSetCustomComparator.java
//.\src\day_8_Sets\TreeSetNumbers.java
//.\src\day_8_stack
//.\src\day_8_stack\BalancedParanthesis.java
//.\src\day_8_stack\Decimal_binary.java
//.\src\day_8_stack\Reverse_String.java
//.\src\day_8_stack\StackDemo.java
//.\src\day_8_Vector
//.\src\day_8_Vector\Copy.java
//.\src\day_8_Vector\Sum.java
//.\src\day_8_Vector\Vector_Demo.java
//.\src\day_8_Vector\Vector_strings.java
//.\src\day_9_Comparable_Comparator
//.\src\day_9_Comparable_Comparator\Book.java
//.\src\day_9_Comparable_Comparator\Book2.java
//.\src\day_9_Comparable_Comparator\City.java
//.\src\day_9_Comparable_Comparator\Emp.java
//.\src\day_9_Comparable_Comparator\Employee.java
//.\src\day_9_Comparable_Comparator\EmployeeDate.java
//.\src\day_9_Comparable_Comparator\EmpMenu.java
//.\src\day_9_Comparable_Comparator\Person.java
//.\src\day_9_Comparable_Comparator\PersonTree.java
//.\src\day_9_Comparable_Comparator\Product2.java
//.\src\day_9_Comparable_Comparator\Products_Sort.java
//.\src\day_9_Comparable_Comparator\StringSort.java
//.\src\day_9_Comparable_Comparator\Student2.java
//.\src\day_9_Comparable_Comparator\Students.java
//.\src\day_9_Comparable_Comparator\Student_Sort.java
//.\src\day_9_FileHandling
//.\src\day_9_FileHandling\AppendToFile.java
//.\src\day_9_FileHandling\CopyFile.java
//.\src\day_9_FileHandling\CountWordsLines.java
//.\src\day_9_FileHandling\DeleteFile.java
//.\src\day_9_FileHandling\DeserializeStudent.java
//.\src\day_9_FileHandling\FileProperties.java
//.\src\day_9_FileHandling\ReadFromFile.java
//.\src\day_9_FileHandling\ReplaceWord.java
//.\src\day_9_FileHandling\ReverseFileContent.java
//.\src\day_9_FileHandling\SearchWord.java
//.\src\day_9_FileHandling\SerializeStudent.java
//.\src\day_9_FileHandling\UserInputToFile.java
//.\src\day_9_FileHandling\WriteToFile.java
//.\story.txt
//.\student.ser
//.\student.txt
//.\Student_Report.csv
//.\test.txt

